Ms 4498 p6 migration
DBCDK/lobby pull request #4
Opened 2023-11-01 13:55 UTC by JensGroenborgAndersen

2023-11-01 14:10 UTC, atmdbc commented on src/main/java/dk/dbc/lobby/rest/Status.java
> +import dk.dbc.dataio.commons.utils.service.ServiceStatus;
Syntes det er lidt mærkeligt at hive noget fra dataio ind i lobby (også selvom det hedder common). 

Men jeg forstår godt problemet med at den gamle ServiceStatus er væk. De par gange jeg er stødt på det, har jeg bare copy-pasted service checket fra microservice-sample-java. Ulempen ved det er så bare at healthcheck url'en ændre sig :/ Så jeg har ikke et godt alternativ.

2023-11-02 11:39 UTC, hwhadbc requested changes

2023-11-02 11:39 UTC, hwhadbc commented on src/main/java/dk/dbc/lobby/rest/Status.java
> +import dk.dbc.dataio.commons.utils.service.ServiceStatus;
Me also no liky.

Gør den andet end bare at svare "200 OK" ?   Den er der vel primært aht. Zabix - som er omtrent lukket ned., alle k8s checks skal bare bruge et simpelt OK.

2023-11-03 14:17 UTC, JensGroenborgAndersen commented on src/main/java/dk/dbc/lobby/rest/Status.java
> +import dk.dbc.dataio.commons.utils.service.ServiceStatus;
Har været ude at genoplive service utils så det nu bor i vores dbc-commons project

2023-11-03 14:18 UTC, merged